name: C/C++ CI

on: [push]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[15.9)'
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Hello world
      run: |
        build.bat --config RelWithDebInfo --build_shared_lib --parallel
      shell: cmd
