name: C/C++ CI

on: [push]

jobs:
  windows-build:
    runs-on: windows-2022
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: build
      run: |
        build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 2022"
      shell: cmd
